### ISSUE TITLE
Contact List shows different people every time I select it

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-transaction-tool#1180]
### Description

If I select "Contact List", I see some contacts. If I click off that tab (say, onto Files) and back onto Contact List, it refreshes, but I see different people -- sometimes completely different, sometimes more, sometimes less.

### Steps to reproduce

Click on Contact List. Wait for it to load. Click on Files. Click on Contact List again.

I'm testing with the testnet signers.

### Version

v0.4.1

### Operating system

macOS

**Comment by yiliev0** [comment]
I attempted to reproduce the issue but was unable to do so. I set up a local environment with 5 users (2 admins and 3 regular users) and manually switched back and forth between the "Contact List" and "Files" tabs. The list remained consistent every time.

I also tested this behavior in the development environment, including changing networks and toggling between tabs. Regardless of these actions, the "Contact List" displayed the same set of users. 

Could you provide more details about the organization where this issue was observed?

https://github.com/user-attachments/assets/730dd5e2-759d-4ed8-9770-fb29b66acd4b

**Comment by jbair06** [comment]
Closed by updated the deployment in devops-gitups. Added POSTGRES_MAX_POOL_SIZE in order to enforce proper pool sizes for all services.
